<div class="card card-register mx-auto mt-5">
        <div class="card-header">Cadastrar Cliente</div>
        <div class="card-body">
            <form>
                <div class="form-group">
                    <div class="form-label-group">
                        <input type="text" id="firstName" class="form-control" placeholder="First name" required="required" autofocus="autofocus">
                        <label for="firstName">Nome</label>
                </div>  </div>
                
                <div class="form-group">
                <div class="form-label-group">
                        <input type="text" id="lastName" class="form-control" placeholder="Last name" required="required">
                        <label for="lastName">CPF</label>
                        </div>  </div>
                
                <div class="form-group">
                <div class="form-label-group">
                    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="required">
                    <label for="inputEmail">RG</label>
                </div>  </div>
                
                <div class="form-group"> 
                <div class="form-label-group">
                    <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="required">
                    <label for="inputEmail">Endereço</label>
                </div> </div>

            <button class="btn btn-primary btn-block">Cadastrar</a>
          </form>
          </div>
              </div>
            </div>