
          <!-- DataTables Example -->
          <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>Cliente</div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Cliente</th>
                      <th>CPF</th>
                      <th>Endereço</th>
                      <th>Telefone</th>
                      <th>E-mail</th>
                      <th></th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                
                  <tbody>

                    <tr>
                      <td>Marina Silva</td>
                      <td>123456789</td>
                      <td>Rua dos expedicionários, 540</td>
                      <td>(43) 994364366</td>
                      <td>marininha@hotmail.com</td>
                      <td><a href="<?php echo $urlBase ?>cliente/consultas/id">Consultas</a></td>
                      <td><a href="<?php echo $urlBase ?>cliente/encomendas/id">Encomendas</a></td>
                      <td><a href="<?php echo $urlBase ?>cliente/editar/id">Editar</a></td>
                      <td><a href="<?php echo $urlBase ?>cliente/inativar/id">Inativar</a></td>
                    </tr>
                   
                  </tbody>
                </table>
              </div>
            </div>
            <div class="card-footer small text-muted">Atualizado às 11:59 PM</div>
          </div>