<!DOCTYPE html>
<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ótica Ótimo - Login</title>

    <!-- Bootstrap core CSS-->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin.css" rel="stylesheet">

  </head>

  <body>

    <div class="container">
    
    <div class="row">
    <div class="col-sm">
        <img width="300" src="img/logo2.jpg">
    </div>
    
    <div class="col-sm">
      <div class="card card-login mx-auto mt-5">
        <div class="card-header">Autenticação</div>
        <div class="card-body">
          <form action="index/login" method="POST">
            <div class="form-group">
              <div class="form-label-group">
                <input type="text" id="inputUser" class="form-control" placeholder="Usuário" required="required" autofocus="autofocus">
                <label for="inputUser">Usuário</label>
              </div>
            </div>
            <div class="form-group">
              <div class="form-label-group">
                <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required="required">
                <label for="inputPassword">Senha</label>
              </div>
            </div>
            <div class="form-group">
              <div class="checkbox">
                <label>
                  <input type="checkbox" value="remember-me">
                  Recuperar senha
                </label>
              </div>
            </div>
            <input type="submit" value="submit" class="btn btn-primary btn-block"  >
          </form>
          <div class="text-center">
            <!--  <a class="d-block small mt-3" href="register.html"></a> -->
            <a class="d-block small" href="forgot-password.html">Esqueci minha senha</a>
          </div>
        </div>
        </div></div></div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  </body>

</html>
