<!DOCTYPE html>
<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $title;  ?> </title>
  
    <!-- Bootstrap core CSS-->
    <link href="<?php echo $urlBase;  ?>vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="<?php echo $urlBase;  ?>vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="<?php echo $urlBase;  ?>vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?php echo $urlBase;  ?>css/sb-admin.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

      <a class="navbar-brand mr-1" href="<?php $urlBase ?>painel">Ótica Ótimo - Painel administrativo</a>

      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Navbar Search -->
      <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar por.." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>

      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">Configurações</a>
            <a class="dropdown-item" href="#">Registro de atividades</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Sair</a>
          </div>
        </li>
      </ul>

    </nav>

    <div id="wrapper">

      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<?php $urlBase ?>painel">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Painel principal</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           
            <span>Módulos</span>
          </a>
          <div class="dropdown-menu show" aria-labelledby="pagesDropdown">
          <div class="dropdown-menu show" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Clientes</h6>
          <a class="dropdown-item" href="<?php echo $urlBase;  ?>cliente/cadastro">Cadastrar</a>
          <a class="dropdown-item" href="/oficinaII/cliente">Gerenciar</a>

          <h6 class="dropdown-header">Fornecedores</h6>
          <a class="dropdown-item" href="/oficinaII/fornecedor/cadastro">Cadastrar</a>
          <a class="dropdown-item" href="/oficinaII/fornecedor">Gerenciar</a>
          
          <h6 class="dropdown-header">Usuários</h6>
          <a class="dropdown-item" href="/oficinaII/usuario/cadastro">Cadastrar</a>
          <a class="dropdown-item" href="/oficinaII/usuario">Gerenciar</a>
          
            
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="charts.html">
            <span>Configurações</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="tables.html">
            <span>Sair</span></a>
        </li>
      </ul>

      <div id="content-wrapper">

        <div class="container-fluid">

          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Painel</a>
            </li>
            <li class="breadcrumb-item active"><?php echo $title; ?> </li>
          </ol>

        
        <?php echo $this->getContent(); ?>
         


        </div>
        <!-- /.container-fluid -->

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright © Ótica Ótimo 2018</span>
            </div>
          </div>
        </footer>

      </div>
      <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Pronto pra sair?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Selecione "Sair" para encerrar sua sessão.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
            <a class="btn btn-primary" href="login.html">Sair</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="<?php echo $urlBase;  ?>vendor/jquery/jquery.min.js"></script>
    <script src="<?php echo $urlBase;  ?>vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="<?php echo $urlBase;  ?>vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Page level plugin JavaScript-->
    <script src="<?php echo $urlBase;  ?>vendor/chart.js/Chart.min.js"></script>
    <script src="<?php echo $urlBase;  ?>vendor/datatables/jquery.dataTables.js"></script>
    <script src="<?php echo $urlBase;  ?>vendor/datatables/dataTables.bootstrap4.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="<?php echo $urlBase;  ?>js/sb-admin.min.js"></script>

    <!-- Demo scripts for this page-->
    <script src="<?php echo $urlBase;  ?>js/demo/datatables-demo.js"></script>
    <script src="<?php echo $urlBase;  ?>js/demo/chart-area-demo.js"></script>

  </body>

</html>
